<div class="btn-toolbar">
    <a href="<?php echo $this->url('crud', array('controller' => 'setor', 'action' => 'novo')) ?>" class="btn btn-primary">Adicionar</a>
</div>

<table class="table table-condensed">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Parent</th>
            <th width="80">Ações</th>
        </tr>
    </thead>
    <?php foreach ($setores as $setor): ?>
    <tr>
        <td><?= $setor->nome ?></td>
        <td><?= $setor->parent ? $setor->parent->nome : '' ?></td>
        <td>
            <a href="<?php echo $this->url('crud', array('controller' => 'setor', 'action' => 'editar', 'id' => $setor->id)) ?>" class="btn btn-small" rel="tooltip" title="Editar"><i class="icon-edit"></i></a>
            <a href="<?php echo $this->url('crud', array('controller' => 'setor', 'action' => 'excluir', 'id' => $setor->id)) ?>" class="btn btn-small btn-danger" rel="tooltip" title="Excluir"><i class="icon-remove"></i></a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>