<h2>Login</h2>
<?php
$form->prepare();
?>

<?php if ($this->error): ?>
<p>Seu noob, loga direito</p>
<?php endif; ?>

<?= $this->form()->openTag($form); ?>

<?= $this->bootstrapRow($form->get('email')); ?>
<?= $this->bootstrapRow($form->get('senha')); ?>
<?= $this->formHidden($form->get('security')); ?>

<div class="control-group">
    <div class="controls">
    <button class="btn">Login</button> ou <a href="">Voltar</a>
    </div>
</div>

<?= $this->form()->closeTag(); ?>