<h2>Adicionar Role</h2>
<?php
$form->prepare();
?>

<?= $this->form()->openTag($form); ?>

<?php if (!$form->get('id')->getValue()): ?>
<legend>Adicionar Usuário</legend>
<?php else: ?>
<legend>Editar Usuário</legend>
<?php endif; ?>

<?= $this->flashMessage(); ?>

<?= $this->formHidden($form->get('id')); ?>
<?= $this->bootstrapRow($form->get('name')); ?>
<?= $this->bootstrapRow($form->get('isAdmin')); ?>
<?= $this->bootstrapRow($form->get('parent')); ?>

<div class="control-group">
    <div class="controls">
    <button class="btn">Salvar</button> ou <a href="">Voltar</a>
    </div>
</div>

<?= $this->form()->closeTag(); ?>