<h2>Cidades - <?= $currentUf ?></h2>

<?php echo $this->flashMessage(); ?>

<div class="pagination pagination-small">
    <ul>
        <?php foreach ($ufs as $uf): ?>
        <li<?= ($currentUf == $uf['uf']) ? ' class="active"' : ''; ?>><a href="<?php echo $this->url('crud', array('controller' => 'cidade', 'uf' => $uf['uf'])) ?>"><?= $uf['uf'] ?></a></li>
        <?php endforeach; ?>
    </ul>
</div>


<table class="table table-condensed">
    <thead>
        <tr>
            <th>Nome</th>
            <th width="100">UF</th>
            <th width="50">Capital</th>
            <th width="80">Ações</th>
        </tr>
    </thead>
    <?php foreach ($cidades as $item):
        $item = (object)$item;
    ?>
    <tr>
        <td><?= $item->nome ?></td>
        <td><?= $item->uf ?></td>
        <td><?= $item->capital ? 'Sim' : 'Não' ?></td>
        <td>
            <a href="<?php echo $this->url('crud', array('controller' => 'cidade', 'action' => 'editar', 'id' => $item->id)) ?>" class="btn btn-small" rel="tooltip" title="Editar"><i class="icon-edit"></i></a>
            <a href="<?php echo $this->url('crud', array('controller' => 'cidade', 'action' => 'excluir', 'id' => $item->id)) ?>" class="btn btn-small btn-danger" rel="tooltip" title="Excluir"><i class="icon-remove"></i></a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>